### ISSUE TITLE
compilation failed in spark-sql.ipynb

### ISSUE THREAD

**Issue by rbavery** [geotrellis/geotrellis-workshop-notebooks#6]
I found this tutorial and it's been super helpful for learning about the Spark ecosystem, thank you! Just wanted to point out that in spark-sql.ipynb, there's a compilation error at

```
col("name")
$"name"
'name
```

```
cell11.sc:1: not found: value col
val res11_0 = col("name")
              ^
Compilation Failed
```

when running the notebook end to end from main.

**Comment by jpolchlo** [comment]
Hey, Ryan!  Long time.  Thanks for finding and reporting this; the fix is imminent.  Makes my day that this resource was useful to someone else.  Feel free to keep checking this out and reporting bugs/recommending changes!

**Comment by rbavery** [comment]
Yeah long time! Thanks for the quick fix and explanation!
